language: cpp
os:
  - linux
  - osx
compiler:
  - gcc
  - clang
env:
  - CXXFLAGS="-Werror"
  - CXXFLAGS="-m32 -Werror"
matrix:
  exclude:
    - os: osx
      env: CXXFLAGS="-m32 -Werror"
dist: focal
before_install: .travis/setup.sh "$TRAVIS_OS_NAME" "$CXX" "$CXXFLAGS"
before_script:
  - ./bootstrap
script:
  - make unittests
  - make algorithmtest
  - ./tests/test_binaries.sh "$TRAVIS_OS_NAME"
before_deploy:
  - ./.travis/build_src_pkg.sh
  - ./.travis/build_static_binaries.sh
  - ./.travis/build_win_binaries.sh
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: SUajXy2Uw1gJ0wJ/MLKogMUzGxrbOtr8xlyW0jFpHp0+3CSdbHoRFIEDyd+ieel2E5c1YXvGWXf7C9EuKtXIn1MG5yxclRvQxmh1ySVraVmuUeAEqtT1oNZV16VEFOF+E7gQFwXThTYA/PrCaAEaxlHnRMXrsTKN5Eohw42LxJE=
  file:
    - "scrm-src.tar.gz"
    - "scrm-x64-static"
    - "scrm-x64-static.tar.gz"
    - "scrm-win32.zip"
    - "scrm-win64.zip"
  on:
    tags: true
    condition: 
      - "$CC = gcc"
      - "$CXXFLAGS == -Werror"
      - "$TRAVIS_OS_NAME == linux"

