language: cpp
os:
- linux
- osx
compiler:
- gcc
- clang
sudo: required
before_install:
- if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo add-apt-repository -y ppa:dns/gnu; fi
- if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi
- if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get update -qq && sudo apt-get install -qqy automake libcppunit-dev valgrind; fi
- if [ "$TRAVIS_OS_NAME" == "linux" -a "$CC" = "gcc" ]; then sudo apt-get install -qqy g++-5 && sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 50; fi
- if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update && brew install cppunit valgrind; fi
before_script:
- ./bootstrap
script:
- ./.travis/build_win_binaries.sh
- make scrm scrm_dbg
- make unittests
- ./tests/test_binaries.sh
- make algorithmtest
before_deploy:
  - ./.travis/build_src_pkg.sh
  - ./.travis/build_static_binaries.sh
deploy:
  provider: releases
  api_key:
    secure: UrEhKzTdSr7NB4ptDYcWKN02XjfgJgN1fNFu8G2a52Jpk1Z3UeenbmKxIDLj11JUlU427br7t1oQyScYSYEGEM5VEI0aWf7D2i9cPfSRD9QYnHOPG2XZE/xgkwWAm0s4TjnTBmudGSxs9g2KRjDXLz1f191jVGIghnHlxw/C9Ok=
  file:
    - "scrm-src.tar.gz"
    - "scrm-x64-static.tar.gz"
  on:
    tags: true
    condition: "$CC = gcc"
    condition: "$TRAVIS_OS_NAME == linux"
