language: cpp
os:
- linux
- osx
compiler:
- gcc
- clang
script:
- make scrm scrm_dbg
- make unittests
- make algorithmtests
- ./tests/test_binaries.sh
- tests/constant_pop_size_many_epoch.sh 
before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq libcppunit-dev valgrind
before_script:
- CXXFLAGS='-O3' ./bootstrap
