language: cpp
os:
  - linux
  - osx
compiler:
  - gcc
  - clang
env:
  - CXXFLAGS="-Werror"
  - CXXFLAGS="-Werror" TEST_CXXFLAGS="--coverage"
  - CXXFLAGS="-m32 -Werror"
  - CXXFLAGS="-Werror -fsanitize=address,undefined -fno-sanitize=float-divide-by-zero -fno-omit-frame-pointer -frtti" LDFLAGS="-fsanitize=undefined,address"
matrix:
  exclude:
    - os: osx
      env: CXXFLAGS="-m32 -Werror"
    - compiler: clang
      env: CXXFLAGS="-Werror" TEST_CXXFLAGS="--coverage"
    - os: osx
      env: CXXFLAGS="-Werror" TEST_CXXFLAGS="--coverage"
    - os: linux
      compiler: gcc
      env: CXXFLAGS="-Werror"
sudo: required
dist: trusty
before_install: .travis/setup.sh "$TRAVIS_OS_NAME" "$CXX" "$CXXFLAGS"
before_script:
  - ./bootstrap
script:
  - make unittests
  - make algorithmtest
  - ./tests/test_binaries.sh "$TRAVIS_OS_NAME"
before_deploy:
  - ./.travis/build_src_pkg.sh
  - ./.travis/build_static_binaries.sh
  - ./.travis/build_win_binaries.sh
deploy:
  provider: releases
  api_key:
    secure: UrEhKzTdSr7NB4ptDYcWKN02XjfgJgN1fNFu8G2a52Jpk1Z3UeenbmKxIDLj11JUlU427br7t1oQyScYSYEGEM5VEI0aWf7D2i9cPfSRD9QYnHOPG2XZE/xgkwWAm0s4TjnTBmudGSxs9g2KRjDXLz1f191jVGIghnHlxw/C9Ok=
  file:
    - "scrm-src.tar.gz"
    - "scrm-x64-static"
    - "scrm-x64-static.tar.gz"
    - "scrm-win32.zip"
    - "scrm-win64.zip"
  on:
    tags: true
    condition: "$CC = gcc"
    condition: "$CXXFLAGS == -Werror"
    condition: "$TRAVIS_OS_NAME == linux"

after_success: .travis/test_coverage.sh "$TRAVIS_OS_NAME" "$CXX" "$CXXFLAGS"
